### ISSUE TITLE
Truffle Compile re-downloads solc even after running Truffle Obtain

### ISSUE THREAD

**Issue by adrianmcli** [trufflesuite/truffle#1835]
## Issue

Truffle Compile re-downloads solc even after running Truffle Obtain. Do note that we use `truffle` to run `truffle obtain`.

But in our tests we use `truffle-compile` by itself (as in we did `npm install truffle-compile` and used it with `require("truffle-compile")`).

## Steps to Reproduce

This is the .travis.yml used [here](https://github.com/trufflesuite/drizzle-utils/blob/master/.travis.yml):

```yml
language: node_js
node_js:
  - "node"
  - "--lts"
cache:
  yarn: true
  directories:
    - node_modules
before_script:
  - "truffle obtain --solc=0.5.2"
```

And this is the `truffle-compile` usage: https://github.com/trufflesuite/drizzle-utils/blob/master/packages/test-chain/compile.js#L3

## Expected Behavior

Since `truffle obtain` is already run, it shouldn't try to download the solidity compiler again.

## Actual Results

Check out this build:

https://travis-ci.org/trufflesuite/drizzle-utils/jobs/508220795

Note that on line 468, it already downloaded the compiler. But on line 539 it tries to do it again. It's able to fetch it in time for this build, but not in other builds.
